### ISSUE TITLE
Update react to 16.13

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1312] opened 2019-08-14 17:55 UTC
Should be fine for Hoist code, but currently blocking due to some of our core dependencies still using the deprecated lifecycle methods.  These result in large / repeated console warnings and I could not find any way to suppress.

Will keep an eye on the following:
* blueprint: palantir/blueprint/issues/3361
* react-select: JedWatson/react-select/issues/3715

**Comment by alexandrubeu** [comment] 2019-10-01 10:09
hoit-react?

**Comment by amcclain** [comment] 2020-01-16 17:34
@peterjcoffman we should revisit this and try an update again, see if any of our dependencies are throwing errors due to use of deprecated/removed lifecycle methods.

Note testing mobile w/the onsen library will be important.

Even if we are still blocked, please update this ticket with our latest findings on which libraries have which specific issues.

**Comment by peterjcoffman** [comment] 2020-01-22 20:20
I have tested this in Toolbox in a not-terribly-systematic way. I see no errors. I see only one warning:

```
backend.js:6 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: AgGridReact
```

So ag-Grid is using deprecated methods. This is not a problem for the time being, but when React 17 rolls around it will break.

**Comment by haynesjm42** [comment] 2020-01-27 15:21
Looks like ag-Grid addressed that in v22, and they are on v22.1 now, we should probably look to get ag-Grid upgraded as well

**Comment by peterjcoffman** [comment] 2020-01-29 20:55
It appears to me like desktop apps will work fine. However, we are getting some warnings on mobile:


```
webpack-internal:///../../hoist-react/node_modules/react-dom/cjs/react-dom.development.js:12357 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Navigator
```
... skipping some lines ...
```
Please update the following components: Page
```

I believe this is caused by Onsen. Both Navigator and Page come from Onsen. and [this issue](https://github.com/OnsenUI/OnsenUI/issues/2680) from Onsen appears to be related.

Unfortunately, I do not believe this is fixable. [Onsen has only a stopgap solution to this problem at present.](https://github.com/OnsenUI/OnsenUI/pull/2694) Also, that stopgap change was merged in September 2019, while the most recent release of Onsen was in July 2019. Onsen does not have a full fix, and the fix it does have is not yet in the released version.

**Comment by lbwexler** [comment] 2020-02-16 19:03
Main Onsen contributor promising a release in March 2020.

**Comment by amcclain** [comment] 2020-02-17 12:50
Should we take a quick stab at forking and building ourselves? Might be good practice? 

See [this note](https://github.com/OnsenUI/OnsenUI/pull/2694#issuecomment-539964134) re. hopes for planned release in November 2019.  Where did you see the promise of a March release?

**Comment by lbwexler** [comment] 2020-02-17 16:00
Saw it on there 'dischord' channel, pretty clearly, recent comment by the guy who seems to be the main maintainer.  Didn't really want to sign up for dischord, as I wasn't familiar enough with it.

**Comment by TomTirapani** [comment] 2020-03-18 14:47
I've contacted the maintainer on discord, asking for confirmation if the March release was still on track. In the mean time, I'll have a go at seeing if I can get it working with a fork of the latest. That way, we'll be in a better position to use the new release if it comes out, or can continue with the fork if it doesn't.

**Comment by TomTirapani** [comment] 2020-03-19 10:10
Response from the maintainer on Discord:

> There is still a release planned of onsenui (and also probably ngx-onsenui once support is added for Angular 9 and Angular CLI). That doesn't include react-onsenui though, which is what you're really looking for. I do know about the deprecated lifecycle methods problem in the React bindings. If it is important to you I can bump it up the list (just after the Angular 9 work and a few small core bugs).

I've asked them to bump the priority of the react-onsenui release, but I think for now we should push ahead with the fork and see if we can past it that way.

**Comment by lbwexler** [comment] 2020-04-26 15:26
@TomTirapani -- Yes, I agree about pushing ahead with a fork.  @amcclain ?

**Comment by TomTirapani** [comment] 2020-04-27 10:26
Yes - been working with Anselm a bit last week on figuring out how to build and distribute our own fork on TC and our npm.

Think we are getting close to a solution - fork is here (https://github.com/xh/OnsenUI), with a modified build script here (https://github.com/OnsenUI/OnsenUI/compare/master...xh:master)

**Comment by lbwexler** [comment] 2020-04-27 12:24
great!   thanks!

**Comment by TomTirapani** [comment] 2020-04-29 13:37
Hi guys

Managed to fork the Onsen packages from master, and build and deploy via Teamcity to our npm:

https://www.npmjs.com/package/@xh/onsenui
https://www.npmjs.com/package/@xh/react-onsenui

With this in place, the react warnings go away as they've replaced the lifecycle methods with their `UNSAFE_xxx` variants.

I was surprised to find that, at least with Toolbox testing, no app changes were required to adjust to the latest version of Onsen. However, looking at the diff between their last release and our fork, there doesn't seem to be anything that could cause issues:

https://github.com/OnsenUI/OnsenUI/compare/1598047284199e77892ea5adde65589341ce80e0...master

So I think we're in a good place to push ahead with testing the react upgrade. PRs below:

https://github.com/xh/hoist-react/pull/1857
https://github.com/xh/toolbox/pull/398

**Comment by amcclain** [comment] 2020-04-29 13:49
That's excellent - thanks again, Tom.

Should we add a brief section at the very top of the README to indicate why we have forked this package? Interesting that we show up in the first page of results when searching for "onsenui" on npm - https://www.npmjs.com/search?q=onsenui - I guess there are not that many other folks who are forking and publishing.

I'm thinking a brief paragraph that indicates this was forked to resolve the React upgrade (w/link to issue assuming they have one) and is not recommended for general use outside of XH + Hoist consulting engagements.

Perhaps we could also figure out how to remove those tags that appear? Might make it slightly less visible. I am not really concerned about any of this, just would hate for some poor student to pick the wrong package and end up with a weird dependency on us.

**Comment by TomTirapani** [comment] 2020-04-29 13:58
Good idea - will do what I can to hide it / lower it in npm search, and republish.

**Closed** 2020-05-08 03:24 UTC
Labels: libraries
