### ISSUE TITLE
Hiding Charts is slow

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1528] opened 2020-01-10 17:28 UTC
We noticed in a client app that having charts on a tab, makes it noticeably slow to move away from the tab.

It appears to be related to actually hiding the tab contents in impl/tabContainer.js. In particular, if we instead *unmount* the tab contents (via `TabContainerModel.unmountOnHide`) things are speedy!

**Comment by peterjcoffman** [comment] 2020-01-10 22:55
It appears this is being caused by resizing the charts. When the chart is hidden, Chart.resizeChart() is called with a width and height of 0. Resizing a chart requires a lot of work (I believe a complete redraw), so this is quite slow.

This also adds some expense to displaying the charts again, i.e. switching back to the tab with charts on it. This requires resizing the charts back to their original size, which is also slow.

The branch [slowChartHiding](https://github.com/xh/hoist-react/tree/slowChartHiding) has a hacked-together fix for this. It seems to work.

@TomTirapani, you added the useOnResize() hook to Chart.js. Would you take a look at this approach and see if it is a reasonable approach?

**Comment by TomTirapani** [comment] 2020-01-13 10:14
Hi Peter,

Not resizing the chart when it becomes hidden makes sense. I think we should make the following changes:

+ We should use `||` on the first condition check here: https://github.com/xh/hoist-react/compare/slowChartHiding#diff-25ff8fda126b607253fe78670c157539R105. If _either_ dimension is 0, we can consider the chart hidden.
+ For code tightness, we could remove the curly braces from each of the early returns and make both one-liners.
+ I think the changes to `Select.js` were pushed to the wrong branch and don't belong as part of this change.

Thanks,
Tom

**Closed** 2020-01-13 16:07 UTC
