### ISSUE TITLE
Mobile routing-based navigation can sometimes cause react to warn in console

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#2483] opened 2021-06-14 15:49 UTC
This occurs in a flagship client app when navigating from certain widgets to their corresponding modules.

<img width="1033" alt="Screen Shot 2021-06-14 at 10 34 05 AM" src="https://user-images.githubusercontent.com/15745614/121921025-9ea45600-cd06-11eb-9e17-f5e27b8607ee.png">

**Comment by lbwexler** [comment] 2021-08-31 03:34
Don -- am having trouble reproducing this.  Perhaps show me in person how to reproduce? 

otherwise I would like to go ahead and close this.

**Comment by febbraiod** [comment] 2021-08-31 13:43
We you running locally? I don't think we get this warning in the deployed app. I will take a look this morning.

**Comment by febbraiod** [comment] 2021-08-31 13:51
Yep just reproduced while running locally.

**Comment by lbwexler** [comment] 2021-09-01 02:19
Yes very easy to reproduce in the client app.  Pretty sure at this point this is related to the advanced use of routing in that app.  Unable to reproduce in toolbox.

**Closed** 2021-09-01 21:13 UTC
Labels: bug, mobile
