### ISSUE TITLE
RelativeTimestamp sometimes needs explicit model 

### ISSUE THREAD

**Issue by PeteDarinzo** [xh/hoist-react#3225] opened 2022-12-19 17:15 UTC
The `relativeTimestamp` component relies on the `@lookup` decorator to provide an instance of its ancestor model to use in its implementation, since it is assumed one will always be available when a component uses a `relativeTimestamp`.

This is not true in the case when a `relativeTimestamp` is used where no ancestor model is available, for example within a column `renderer` function. In this case, the `relativeTimestamp`'s model must be provided using `model: this` in its props. This is not an intended behavior, and a model prop is not specified in the RealtiveTimestampProps interface.

**Comment by amcclain** [comment] 2022-12-23 13:47
Good catch and write-up here.  Tagging for our v54 release as it seems like this is one we should hopefully be able to decide on and fix up pretty quickly, and would be good to get in to our first TS release.

**Comment by lbwexler** [comment] 2022-12-23 20:22
Hi -- Understand that we are having trouble reproducing the failure where `lookup('*')` fails.  Pete and I will try to nail that down in the client app, but in the meantime, perhaps we should avoid doing that lookup at all, if we are provided with a timestamp directly?

**Comment by lbwexler** [comment] 2023-02-15 23:47
Reopening this as I am still seeing problems with rendering a relativeTimestamp() in a grid with the latest hoist ?!?

Note that we might want to provide a built-in column here -- its not even clear that most users want the fairly expensive updating `relativeTimestamp` component in their renderer vs. a one-time call to`getRelativeTimestamp` -- but they probably will get that -- its very subtle.   In my case, happier to use the one time function call to get a string, so avoiding the error....

**Comment by TomTirapani** [comment] 2023-02-16 09:29
I'll need to check, but I think I created a column in a client app that both uses the `getRelativeTimestamp` function (rather than the component) *and* autoupdates itself...

**Comment by lbwexler** [comment] 2023-03-02 21:31
I think you are right tom -- `getRelativeTimestamp()` is just potentially misleading in any app that is not auto-refreshing not just the grid.

Out of curiosity, do you recall why you did not want to use the component?  Was it pre ag-Grid React, due to this bug, or something else?

**Comment by TomTirapani** [comment] 2023-03-03 09:40
IIRC it was due to performance concerns pre ag-Grid React - we didn't want to have thousands of `elementRenderers` so were looking for a way to do it with `renderers` but keep them up to date.

**Comment by lbwexler** [comment] 2023-03-09 19:04
Closing this yet again -- unable to reproduce.

**Closed by lbwexler** 2023-03-09 19:04 UTC
Labels: bug, technical
