### ISSUE TITLE
Grid column cellClass property adds to cell classes instead of replacing the custom class on data update

### ISSUE THREAD

**Issue by pauldelano** [xh/hoist-react#1791] opened 2020-03-23 21:27 UTC

**Comment by amcclain** [comment] 2020-03-24 09:40
This is a dupe of #1331 - please see that ticket for details.  Proposed solution is to deprecate the existing functions and encourage the use of `rowClassRules` and `cellClassRules` by accepting those as configs on `GridModel`.

**Closed by amcclain** 2020-03-24 09:40 UTC
