### ISSUE TITLE
Check tracking of formModel.values in an addReaction function.

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#2087] opened 2020-09-22 21:59 UTC
Have noticed in that a reaction set up in a model constructor to track the value of a formfield
does not actually track that value unless the formModel is marked as @observable

```
@HoistModel
export class LookupTabModel {

   @managed
   @observable   // <---- THIS SHOULD NOT BE NECESSARY
    someFormModel = new FormModel({fields: [{name: 'someFieldName'}]});

    constructor() {
        this.someFormModel.init();

        this.addReaction({
            track: () => this.someFormModel.values.someFieldName,
            run: () => {
                this.doSomething();
            }
        });
  }
}
```

**Comment by lbwexler** [comment] 2020-09-23 08:52
Hi Colin -- I checked this in toolbox, and am unable to reproduce.

I originally suspected perhaps there is some problem with the observing the results of the values proxy, but that now seems unlikely to me -- app use this way of getting values for observation constantly

Let's come up with a reproducible example in toolbox, or look at the app in question and see whats going on -- my strong suspicion is that this is an application issues.

**Comment by lbwexler** [comment] 2020-09-24 18:00
Closing this --- I don't think this is a hoist issue -- as discussed with Colin, probably related to a number of other things going on in the application in question

**Closed by lbwexler** 2020-09-24 18:00 UTC
