### ISSUE TITLE
Upgrade the @managed to automatically handle deleting hoist models when replacing them

### ISSUE THREAD

**Issue by jskupsik** [xh/hoist-react#3204] opened 2022-11-18 19:34 UTC
Our new inspector UI revealed that we had some memory leaks occurring whenever we were creating new HoistModels inside of a HoistModel outside of initialization (for example, creating new HoistModels in the `doLoadAsync()` method). We currently fix this by making sure to call `XH.safeDestroy(this.managedModel);` before `this.managedModel = new HoistModel();`.

Dealing with memory management so directly is not what one should be thinking about when working in JavaScript. This leaves the option for a developer to very easily create unintended memory leaks; it would be better if this boilerplate could be handled by hoist.

I have been thinking about adding to the functionality of the `@managed` annotation. This annotation currently causes the `XH.safeDestroy()` method to be called on the object when their parent is destroyed. It would be ideal if that annotation also created a setter which called `XH.safeDestroy()` on the old model before assigning the new one to that variable. It should be null safe and potentially check `oldModel === newModel` to make sure it isn't going to delete itself.

This would change the behavior of existing `this.managedModel = new HoistModel();` code and may be a breaking change if such a model was being used in dangerous ways, but it should be compatible and an upgrade to all 'proper' use cases of the annotation. It should also be compatible with existing code that manually calls `XH.safeDestroy()` before setting the field.

**Comment by ghsolomon** [comment] 2022-11-18 22:46
Great idea!

**Comment by lbwexler** [comment] 2022-11-23 11:57
It is a great idea, and thanks for the tremendous detail.

Am nervous about backward compatibility -- and specifically what we are now defining as "proper" use of the decorator.  A particular example that worries me is the case that an app is using it to store an array of objects that its managing.   The app cleans these up as it goes, resetting the array to a new array, and cleaning up the abandoned objects.  It relies on @managed to simply  clean-up the final version of the array upon its own destruction.

The problem is, that with the new behavior, any set will cause `XH.safeDestroy()` to be called on the old copy of the array which might contain values we are still using.

I don't think this is a theoretical use-case -- would have to look at where we do it, but think its actually fairly common, and an obvious choice for an app trying to maintain a collection of managed objects.

**Comment by amcclain** [comment] 2024-06-20 17:43
Closing as not immediately actionable - can re-open if this comes up again as a priority, as there are some great ideas (and cautions) here.

**Closed by amcclain** 2024-06-20 17:43 UTC
Labels: technical, performance
