### ISSUE TITLE
Improve performance of autosizing with AG27

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#2996] opened 2022-05-06 20:00 UTC
We are seeing an ugly delay in rendering a particular grid in a flagship client app with the AG27 upgrade. 

Appears to be related to autosizing a grid with a lot  of columns (29) and a lot of (although not a tremendous amount) of rows. Let's call it ~2500. The grid renders with the rows in place, but no visible data. After something like 3 full seconds the grid fills in.

When we turn autosizing off this problem goes away.

**Comment by lbwexler** [comment] 2022-05-06 22:05
@TomTirapani -- assigning you and I to see if we can do anything here.  Realize there may not be a simple solution here.  At the very least want to look at with you and understand the scope of the problem

**Comment by TomTirapani** [comment] 2022-05-10 15:42
Don showed me how to reproduce this, and I spent some time investigating - please see PR: https://github.com/xh/hoist-react/pull/3001

The "rows without data" was due to the autosize beginning before AG has finished rendering the rows. It appears that since v27, AG takes a little longer to render the rows. Increasing our [existing wait()](https://github.com/xh/hoist-react/pull/3001/files#diff-a2de0175ecc720a2fc3b534c0e1b01de3885368a1fe6b5a58a1f9f06589ee399R1223) allowed the rows to render prior to starting the autosize.

I also looked at the performance of the autosize in general. The bulk of the time is taken up by collecting the rendered values for records, in columns that display elements that need to be [converted to static markup](https://github.com/xh/hoist-react/blob/develop/cmp/grid/impl/ColumnWidthCalculator.js#L103).

Unfortunately, I'm not sure what we can do about this. Now that renderers can return elements, we need to do this conversion in order to be able to sample / size them later. Note that running react in prod mode improved the speed of this step slightly (~30% improvement), so it might be better in deployed apps.

I added [this line](https://github.com/xh/hoist-react/pull/3001/files#diff-679de26b40b407185f61bc73366c115fffb6abbf82057e1c35aa40e43592d798R112) to limit the number of records we sample, which halved the overall time for this largish grid. However, this change introduces the risk that a record with a long value is excluded. On the other hand, if your grid has more than a 1000 records, outliers are less likely to be encountered by the user, and an "approximate" width is more useful than an "exact" width. I'm not too sure about this last change, and happy to discuss.

**Comment by lbwexler** [comment] 2022-05-11 21:04
Closing this for now, reflecting Tom's substantial improvements for v49.  We will keep our eyes on it

**Closed by lbwexler** 2022-05-11 21:04 UTC
