### ISSUE TITLE
Focus delay when using custom component as inline grid editor

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#1992] opened 2020-07-10 17:47 UTC
We have a client app in which there are a number of editable cells that users want to quickly add values to and then tab through to the next cell. 

To facilitate, we have wrapped a variety of HoistInputs in React Component classes to be registered with ag-grid as specified in their docs. However, we found the need to "createObservableRef" on the HoistInput, react to that, and then query the DOM for the underlying input in order to "manually" place the focus on the input, otherwise the input will not get the focus at all.

This seems to have created a noticeable and annoying delay between the time the user presses TAB and the input receiving the focus to start accepting new input. Effectively the first one or two keystrokes get "swallowed", forcing the user to constantly correct the content and deliberately slow down to a borderline unacceptable pace.

This problem seems to go away when using ag-grid's built in inputs, but then we lose a bunch of desirable behavior from our inputs.

**Comment by amcclain** [comment] 2021-06-02 15:36
@haynesjm42 and @febbraiod can you please review and close if we've addressed these concerns in the latest inline editing work?

**Comment by lbwexler** [comment] 2021-06-30 18:50
Fortunately, I can't reproduce this using our new v41 editing.  Closing.

We can always reopen if needed.

**Closed by lbwexler** 2021-06-30 18:50 UTC
Labels: client-request, grid
