### ISSUE TITLE
Create Popover "menu button" component

### ISSUE THREAD

**Issue by ghsolomon** [xh/hoist-react#2964] opened 2022-04-20 21:05 UTC
Create a wrapper component around the existing `popover` with the ability to render the target as `disabled` or `null` when there is no `content` (menu items).

**Comment by amcclain** [comment] 2022-04-21 18:29
Closing as a dupe of long-outstanding #2400 - but will bump that old ticket up for near-term work

**Closed by amcclain** 2022-04-21 18:29 UTC
