### ISSUE TITLE
XH.fetchService.fetch() throws on 307 Temporary Redirect

### ISSUE THREAD

**Issue by TomTirapani** [xh/hoist-react#1347] opened 2019-09-03 16:01 UTC
If a fetch request returns a 307 Temporary Redirect, an exception is thrown from the following line:

https://github.com/exhi/hoist-react/blob/develop/svc/FetchService.js#L149

I think since we are setting `redirect: 'follow'` in our fetch options, we should respect that and not throw on the `3XX Redirect` statuses. `Response.ok` only returns true for 200-299. Currently working around this in a client app by using the fetch api directly.

**Comment by lbwexler** [comment] 2019-10-10 19:44
@TomTirapani   -- @cnrudd  has looked in to this carefully and is pretty sure that the redirects are followed fine, and the problem is with the JSON parsing of an HTML result.  

Can you confirm with him and close this?

**Comment by TomTirapani** [comment] 2019-10-11 10:42
Having looked more closely at the issue, it seems the problem I was seeing is due to the API not returning a `Location` header with the `307` redirect. Instead, it responded with the expected content but a `307` status.

With a `Location` header, fetch will perform a follow up request at the correct resource, so the final response will return a `200` and therefore `Response.ok`. This is the correct behaviour and we fully support it:

<img width="727" alt="Screenshot 2019-10-11 at 11 36 54" src="https://user-images.githubusercontent.com/3017757/66645578-bff09d00-ec1b-11e9-83c2-1fac585f2edc.png">

However, without a `Location` header, the final response will be a `307` and it will fail the `Response.ok` check.

So I think this was a case of a misconfigured API. I will work with the API team and ask them if they can update the API response.

Apologies for the misdirection :(

**Closed** 2019-10-11 13:42 UTC
