### ISSUE TITLE
Mobile Column Headers Freeze and Persist When Dragged Between Pinned/Unpinned State

### ISSUE THREAD

**Issue by petradish** [xh/hoist-react#1754] opened 2020-03-05 18:06 UTC
![Screenshot_20200305-123057](https://user-images.githubusercontent.com/49966727/76011074-fa681880-5ee1-11ea-8eb8-168234711e67.png)
![Screenshot_20200305-123050](https://user-images.githubusercontent.com/49966727/76011084-fcca7280-5ee1-11ea-8e78-23dd9d403380.png)

On mobile, dragging column headers between pinned (first column) and unpinned states causes them to freeze at the dividing line. They also persist in browser when you navigate away from the grid.

**Comment by peterjcoffman** [comment] 2020-03-05 18:21
Interestingly, I can only reproduce this in Chrome's device emulation or on an actual phone. The problem does not occur when visiting the mobile site on a desktop browser.

**Comment by lbwexler** [comment] 2020-03-05 19:12
well, that's good news

**Comment by haynesjm42** [comment] 2020-03-05 19:44
Usually see this behavior when an exception is thrown in ag-grid code, or in an ag-grid callback/renderer. Any errors in the console when this happens?

**Comment by petradish** [comment] 2020-03-05 19:51
No errors logged :( It also looks like this happens for make visible/hidden using dragging as well. Column reordering does not trigger this bug

**Comment by TomTirapani** [comment] 2020-03-06 13:21
Can easily reproduce this on device and in Chrome device emulation.

Interestingly, unable to reproduce this with the example over at https://www.ag-grid.com/example.php (you have to pin the column in desktop mode, then switch to device emulation), so I think it must be something we're introducing

**Comment by lbwexler** [comment] 2020-03-10 17:11
We need to prioritize this one.  This is a major bug.  My apologies for misunderstanding Peter's original comment above.

**Comment by lbwexler** [comment] 2020-03-10 19:00
Closing this -- with John's fixed.  We can obviously re-open if the demand ever comes for dragging columns on mobile.  The bug is pretty obvious, so we'll at that point immediately if it still a problem

**Closed by lbwexler** 2020-03-10 19:00 UTC
