### ISSUE TITLE
Charts export button throws "Uncaught Error"

### ISSUE THREAD

**Issue by mpeckerman** [xh/hoist-react#1429] opened 2019-10-29 20:27 UTC
1. Navigate to Toolbox->
2. Select Charts tab->
Select Line subtab->
4. Click Export Button->

5. Select 'Download PNG image'
highstock.js:12 Uncaught Error: Highcharts error #28: www.highcharts.com/errors/28
    at m (highstock.js:12)
    at Object.e.error (highstock.js:12)
    at f (offline-exporting.js:20)
    at t.Chart.getSVGForLocalExport (offline-exporting.js:20)
    at t.Chart.exportChartLocal (offline-exporting.js:22)
    at t.Chart.onclick (offline-exporting.js:22)
    at HTMLDivElement.onclick (exporting.js:26)

6. Select 'Download SVG vector image' 
highstock.js:12 Uncaught Error: Highcharts error #28: www.highcharts.com/errors/28
    at m (highstock.js:12)
    at Object.e.error (highstock.js:12)
    at f (offline-exporting.js:20)
    at t.Chart.getSVGForLocalExport (offline-exporting.js:20)
    at t.Chart.exportChartLocal (offline-exporting.js:22)
    at t.Chart.onclick (offline-exporting.js:23)
    at HTMLDivElement.onclick (exporting.js:26)

7. Select 'Download CSV image' 
Uncaught TypeError: t.find is not a function
    at export-data.js:18
    at Array.forEach (<anonymous>)
    at t.Chart.getDataRows (export-data.js:17)
    at t.Chart.getCSV (export-data.js:20)
    at t.Chart.downloadCSV (export-data.js:24)
    at t.Chart.onclick (export-data.js:28)
    at HTMLDivElement.onclick (exporting.js:26)
| (anonymous) | @ | export-data.js:18
-- | -- | -- | --
  | t.Chart.getDataRows | @ | export-data.js:17
  | t.Chart.getCSV | @ | export-data.js:20
  | t.Chart.downloadCSV | @ | export-data.js:24
  | onclick | @ | export-data.js:28
  | onclick | @ | exporting.js:26

**Comment by cnrudd** [comment] 2019-10-30 13:32
I am able to reproduce this issue in toolbox.xh.io
It does not happen when running toolbox locally at http://localhost:3000

This suggests the issue is caused by minification or transpilation at build time.

**Comment by lbwexler** [comment] 2019-10-30 13:45
Thanks for troubleshooting.  Need to keep pushing on this one.  Let's check with Don and see if he sees this on client project using v28

**Comment by cnrudd** [comment] 2019-10-30 19:11
Hi,

By running production builds of a client GUI on my machine, I was found that the problem can be resolved by setting mangle: false here:
https://github.com/xh/hoist-dev-utils/blob/develop/configureWebpack.js#L511

Using `false` rather than `true` resulted in a bundle size that was 9kb more:  617kb vs 608kb
The small increase seems acceptable to me if it reduces build risks.

The error is happening on this line of the highcharts offline exports module:
https://github.com/highcharts/highcharts/blob/master/js/modules/offline-exporting.src.js#L192

`dummySVGContainer = doc.createElement('div')`
When 'mangled'   it is:
`p=f.createElement('div')`
and `f` is undefined.

I could dig deeper into which of these terser mangle options:
https://github.com/terser/terser#mangle-options
or compress options:
https://github.com/terser/terser#compress-options

might provide a more specific solution, but I'm not sure how long will take or how bullet proof the solution would be.

Let me know how you'd like to proceed.

**Comment by lbwexler** [comment] 2019-10-30 19:28
Would like @amcclain  to weigh in.  This is a lot like a similar problem he found with mangling in toolbox:

https://github.com/xh/toolbox/commit/fbb00cd8da7a703ba7edf1a2977a125c0ce4c59e

Maybe it is time to stop mangling? That bundle-size difference does seem miniscule

Would like to get this into a v28.1.2 release


For my 2 cents, would

**Comment by lbwexler** [comment] 2019-11-01 18:26
spoke with @atm -- we are going to stop mangling our code.  Hard to argue with that! :-)

**Comment by lbwexler** [comment] 2019-11-01 19:03
This gets fixed by 
https://github.com/xh/hoist-dev-utils/pull/19

**Comment by cnrudd** [comment] 2019-11-04 22:46
Closing without making changes to our code because the issue has resolved itself.
If you are experiencing this issue, delete your yarn.lock file or run `yarn upgrade`.
Be sure you are getting Highcharts >= 7.2.1
We think the issue was fixed by this change in Highcharts:
https://github.com/highcharts/highcharts/issues/11690
https://github.com/highcharts/highcharts/pull/11833

**Closed by cnrudd** 2019-11-04 22:46 UTC
