### ISSUE TITLE
Row gaps seen after AG Grid 27 upgrade

### ISSUE THREAD

**Issue by saba-mo** [xh/hoist-react#3036] opened 2022-06-03 19:46 UTC
With the AG Grid 27 upgrade, several client apps have experienced periodic row gaps, not always consistently reproducible. One scenario involved a combination of having a pinned column and scrolling down the grid before loading new data and seeing the gap, but it has also been seen in other scenarios that do not involve pinned columns or scrolling.

**Comment by febbraiod** [comment] 2022-06-09 11:47
Lee indicates that at least one permutation of this is easy to reproduce in toolbox -- simply set any filter immediately after loading the data (as discovered by jBar).

**Comment by lbwexler** [comment] 2022-06-21 13:35
The scenario Don mentions is in the toolbox `gridTune` example and is fixed by this.
The scenario saba mentions also seems to be fixed by this (but it much more difficult to reproduce generally)

**Comment by lbwexler** [comment] 2022-06-22 01:00
Don has a scenario in a client app where we are seeing this error mode, keeping it open and looking at that.  
We still think the fix in the related PR is solid and moves the ball forward

**Closed** 2022-08-11 15:50 UTC
Labels: bug, grid
